/*
 * Open Thandor
 * Project: https://github.com/idkFoxes/open-thandor/tree/main
 * File: https://github.com/idkFoxes/open-thandor/blob/main/include/thandor/platform/bootstrap/image.h
 */

#ifndef THANDOR_PLATFORM_BOOTSTRAP_IMAGE_H
#define THANDOR_PLATFORM_BOOTSTRAP_IMAGE_H

/*
Original data image.

thandor.exe keeps code and data in one writable .text section at fixed addresses and has no
relocations. The recovered code addresses globals, tables and literals at those addresses
(generated/globals.h), so the rebuilt executable maps the original image at 0x400000 before
anything else runs and redirects code pointers stored in it to the recovered C functions.
The original machine code is mapped non-executable and never runs.
*/

typedef struct ThandorFunctionMapEntry {
    unsigned originalAddress;
    void *function;
} ThandorFunctionMapEntry;

/* Sorted by originalAddress; generated by tools/gen_function_map.py. */
extern const ThandorFunctionMapEntry g_ThandorFunctionMap[];
extern const unsigned g_ThandorFunctionMapCount;

/* Recovered C function whose original entry address is originalAddress, or NULL when no mapped
   function starts there (binary search of g_ThandorFunctionMap). */
void *Thandor_FunctionAtOriginalAddress(unsigned originalAddress);
/* Original entry address of a recovered C function, or 0 when it is not in g_ThandorFunctionMap. */
unsigned Thandor_OriginalAddressOfFunction(const void *function);

/* Restarts the process suspended with the original image range reserved. Returns -1 in the
   restarted process, otherwise the exit code to return. */
int Thandor_RelaunchWithReservedImage(void);

/* Maps thandor_original.exe (next to the executable) at its image base. Returns 0 on success,
   otherwise shows a message box and returns nonzero. */
int Thandor_MapOriginalImage(void);

/* Appends one line to thandor.log next to the executable. */
void Thandor_Log(const char *format, ...);

/* Appends `reason value` and the current call stack to thandor.log. */
void Thandor_LogStack(const char *reason, unsigned value);

/* Nonzero when [address, address + size) is committed, readable memory (diagnostics). */
int Thandor_IsReadable(const void *address, unsigned size);
/* Debug tool: sets the main window caption (ANSI). */
void Thandor_SetWindowTitle(void *window, const char *title);
unsigned Thandor_TickCount(void);
void Thandor_SleepMs(unsigned milliseconds);
/* Returns nonzero when the UTF-16 path names an existing directory. */
int Thandor_DirectoryExistsW(const unsigned short *path);
/* Self-tests: an executable copy of original code bytes (position-independent functions only). */
void *Thandor_LoadOriginalCodeCopy(unsigned address, unsigned size);
/* Test aid (OPEN_THANDOR_SCRIPT `ingame`): counts in-game session frames, i.e. frames after the
   level has finished loading. */
extern volatile unsigned g_TestAidInGameFrames;
#ifdef THANDOR_TEST_AIDS
/* Test aids for a local two-instance network test (not in the original):
   OPEN_THANDOR_MULTI_INSTANCE=1 lets a second instance start although a game window exists;
   OPEN_THANDOR_NET_PORT=<n> binds this instance's UDP socket to port n instead of the game port. */
int Thandor_TestAidAllowSecondInstance(void);
/* Nonzero when OPEN_THANDOR_SCRIPT is set (scripted input; the real mouse is then ignored). */
int Thandor_TestAidScriptActive(void);
unsigned Thandor_TestAidNetworkBindPort(unsigned gamePort);
/* OPEN_THANDOR_NETLOG=1: logs every datagram (direction, sockaddr_in, size, first dwords). */
void Thandor_TestAidLogDatagram(const char *direction, const void *sockaddrIn, unsigned byteCount,
                                const void *buffer);
/* Windowed test aid (not in the original), so two instances fit side by side on one monitor:
   OPEN_THANDOR_WINDOWED=1 runs the game in a normal captioned window at OPEN_THANDOR_WINDOW_X /
   OPEN_THANDOR_WINDOW_Y (default 0,0) instead of full-screen exclusive. DirectDraw stays at DDSCL_NORMAL,
   the display mode is not changed (the desktop colour depth is used), the software renderer blits into the
   client area through a clipper and DirectInput takes the mouse non-exclusively. Only the software renderer
   runs windowed: Graphics_Init enumerates no Glide or Direct3D devices then, so every adapter is a plain
   DirectDraw (software) one. Off by default. */
int Thandor_TestAidWindowed(void);
/* Creates the windowed main window (client 640x480 until the first display mode sizes it). */
void *Thandor_TestAidCreateWindowedMainWindow(const char *className, const char *title, void *instance);
/* Resizes the window so that its client area is width x height. */
void Thandor_TestAidSetWindowClientSize(void *window, unsigned width, unsigned height);
/* Screen position of the window's client origin. */
void Thandor_TestAidClientOriginOnScreen(void *window, int *x, int *y);
#endif
/* Full path of the running executable (ANSI), independent of how it was started. */
void Thandor_GetExecutablePathA(char *out, unsigned capacity);

/* Symbol name (+offset) of an address in this executable, for diagnostics. */
const char *Thandor_SymbolName(const void *address);

/* Writes crash.log next to the executable with a symbolized stack on unhandled exceptions, and
   hang.log when no frame has been presented for a few seconds (see g_ThandorFrameHeartbeat). */
void Thandor_InstallCrashHandler(void);

/* Incremented on every presented frame; the hang detector watches it. */
extern volatile long g_ThandorFrameHeartbeat;

#endif /* THANDOR_PLATFORM_BOOTSTRAP_IMAGE_H */
