/*
 * Open Thandor
 * Project: https://github.com/idkFoxes/open-thandor/tree/main
 * File: https://github.com/idkFoxes/open-thandor/blob/main/src/platform/debug/font.cpp
 * Project code (not in the original game)
 */

#include <string.h>
#include <thandor/thandor.h>
#include <thandor/platform/debug/font.h>

/* 5x7 debug font: each entry is the character followed by its 7 rows of 5 pixels, top row first; in a row the
   leftmost pixel is bit 4. The glyphs are capitals stored under lower-case keys (DebugFont_DrawText folds
   A-Z to a-z). In the table X is a set pixel and o a clear one, so each glyph reads as a picture. */
#define FONT_ROW(a,b,c,d,e) ((a) << 4 | (b) << 3 | (c) << 2 | (d) << 1 | (e))
#define X 1
#define o 0

static const uint8_t g_DebugFont5x7[][8] = {
  {' ', FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o)},
  {'.', FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,X,X,o,o),
        FONT_ROW(o,X,X,o,o)},
  {'/', FONT_ROW(o,o,o,o,X),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,X,o,o,o),
        FONT_ROW(o,X,o,o,o),
        FONT_ROW(X,o,o,o,o)},
  {':', FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,X,X,o,o),
        FONT_ROW(o,X,X,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,X,X,o,o),
        FONT_ROW(o,X,X,o,o),
        FONT_ROW(o,o,o,o,o)},
  {'-', FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(X,X,X,X,X),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o)},
  {'_', FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(o,o,o,o,o),
        FONT_ROW(X,X,X,X,X)},
  {'0', FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,X,X),
        FONT_ROW(X,o,X,o,X),
        FONT_ROW(X,X,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,o)},
  {'1', FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,X,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,X,X,X,o)},
  {'2', FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,o,o,o,X),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,X,o,o,o),
        FONT_ROW(X,X,X,X,X)},
  {'3', FONT_ROW(X,X,X,X,X),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,o)},
  {'4', FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,X,X,o),
        FONT_ROW(o,X,o,X,o),
        FONT_ROW(X,o,o,X,o),
        FONT_ROW(X,X,X,X,X),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,o,X,o)},
  {'5', FONT_ROW(X,X,X,X,X),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,X,X,X,o),
        FONT_ROW(o,o,o,o,X),
        FONT_ROW(o,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,o)},
  {'6', FONT_ROW(o,o,X,X,o),
        FONT_ROW(o,X,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,o)},
  {'7', FONT_ROW(X,X,X,X,X),
        FONT_ROW(o,o,o,o,X),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,X,o,o,o),
        FONT_ROW(o,X,o,o,o),
        FONT_ROW(o,X,o,o,o)},
  {'8', FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,o)},
  {'9', FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,X),
        FONT_ROW(o,o,o,o,X),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,X,X,o,o)},
  {'a', FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,X,X,X,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X)},
  {'b', FONT_ROW(X,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,X,X,X,o)},
  {'c', FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,o)},
  {'d', FONT_ROW(X,X,X,o,o),
        FONT_ROW(X,o,o,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,X,o),
        FONT_ROW(X,X,X,o,o)},
  {'e', FONT_ROW(X,X,X,X,X),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,X,X,X,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,X,X,X,X)},
  {'f', FONT_ROW(X,X,X,X,X),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,X,X,X,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o)},
  {'g', FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,X,X,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,X)},
  {'h', FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,X,X,X,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X)},
  {'i', FONT_ROW(o,X,X,X,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,X,X,X,o)},
  {'j', FONT_ROW(o,o,X,X,X),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(X,o,o,X,o),
        FONT_ROW(o,X,X,o,o)},
  {'k', FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,X,o),
        FONT_ROW(X,o,X,o,o),
        FONT_ROW(X,X,o,o,o),
        FONT_ROW(X,o,X,o,o),
        FONT_ROW(X,o,o,X,o),
        FONT_ROW(X,o,o,o,X)},
  {'l', FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,X,X,X,X)},
  {'m', FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,X,o,X,X),
        FONT_ROW(X,o,X,o,X),
        FONT_ROW(X,o,X,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X)},
  {'n', FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,X,o,o,X),
        FONT_ROW(X,o,X,o,X),
        FONT_ROW(X,o,o,X,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X)},
  {'o', FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,o)},
  {'p', FONT_ROW(X,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,X,X,X,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o)},
  {'q', FONT_ROW(o,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,X,o,X),
        FONT_ROW(X,o,o,X,o),
        FONT_ROW(o,X,X,o,X)},
  {'r', FONT_ROW(X,X,X,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,X,X,X,o),
        FONT_ROW(X,o,X,o,o),
        FONT_ROW(X,o,o,X,o),
        FONT_ROW(X,o,o,o,X)},
  {'s', FONT_ROW(o,X,X,X,X),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(o,X,X,X,o),
        FONT_ROW(o,o,o,o,X),
        FONT_ROW(o,o,o,o,X),
        FONT_ROW(X,X,X,X,o)},
  {'t', FONT_ROW(X,X,X,X,X),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o)},
  {'u', FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,X,X,o)},
  {'v', FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,o,X,o),
        FONT_ROW(o,o,X,o,o)},
  {'w', FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,X,o,X),
        FONT_ROW(X,o,X,o,X),
        FONT_ROW(X,o,X,o,X),
        FONT_ROW(o,X,o,X,o)},
  {'x', FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,o,X,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,X,o,X,o),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X)},
  {'y', FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(X,o,o,o,X),
        FONT_ROW(o,X,o,X,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,o,X,o,o)},
  {'z', FONT_ROW(X,X,X,X,X),
        FONT_ROW(o,o,o,o,X),
        FONT_ROW(o,o,o,X,o),
        FONT_ROW(o,o,X,o,o),
        FONT_ROW(o,X,o,o,o),
        FONT_ROW(X,o,o,o,o),
        FONT_ROW(X,X,X,X,X)},
};

#undef X
#undef o
#undef FONT_ROW

/* Draws text at 1x scale with a black box behind it through the fill slot (g_GraphicsFramebufferFillRectArgb):
   one fill for the box, then one per horizontal run of set pixels in each glyph row. Going through the slot
   (instead of writing the framebuffer pixels) lets the GPU backend record the label as Draw2D FILL items. Both
   colours are opaque, so the software fill writes them through the pixel pack tables, which are the identity
   unless the display settings changed brightness or contrast. */
void DebugFont_DrawText(int x0, int y0, const char *text)
{
  SoftwareFramebufferAccess *framebuffer = g_FramebufferAccess;
  int length = (int)strlen(text);
  int boxWidth = length * 6 + 2;
  int clipMaxX;
  int clipMaxY;
  int c;
  if ((framebuffer == nullptr) || (framebuffer->bytesPerPixel != 4)) {
    return;
  }
  clipMaxX = (int)g_FramebufferWidth;
  clipMaxY = (int)g_FramebufferHeight;
  g_GraphicsFramebufferFillRectArgb(clipMaxY, clipMaxX, 0, 0, y0 + 9, x0 + boxWidth, y0, x0,
                                    DEBUG_FONT_BOX_COLOR_32BPP, framebuffer);
  for (c = 0; c < length; c++) {
    char ch = text[c];
    const uint8_t *glyph = nullptr;
    unsigned g;
    int y;
    if ((ch >= 'A') && (ch <= 'Z')) ch = (char)(ch - 'A' + 'a');
    for (g = 0; g < sizeof g_DebugFont5x7 / sizeof g_DebugFont5x7[0]; g++) {
      if (g_DebugFont5x7[g][0] == (uint8_t)ch) { glyph = g_DebugFont5x7[g] + 1; break; }
    }
    if (glyph == nullptr) continue;
    for (y = 0; y < 7; y++) {
      int x = 0;
      while (x < 5) {
        int runStart;
        if (((glyph[y] >> (4 - x)) & 1) == 0) { x++; continue; }
        runStart = x;
        while ((x < 5) && ((glyph[y] >> (4 - x)) & 1)) x++;
        g_GraphicsFramebufferFillRectArgb(clipMaxY, clipMaxX, 0, 0, y0 + 1 + y + 1, x0 + 1 + c * 6 + x,
                                          y0 + 1 + y, x0 + 1 + c * 6 + runStart, DEBUG_FONT_TEXT_COLOR_32BPP,
                                          framebuffer);
      }
    }
  }
}
