"""Generate extern declarations and definitions for the global variables
listed in the raw Ghidra export.

The export contains a block of top-level data declarations such as

    MemoryApiTable g_MemoryApi;
    word[256] g_PackageLastErrorPath;
    undefined Random_NextPrimary;        <- function label, not data

This script converts them to valid C (array suffix after the name), drops
labels that name functions, and writes

    include/thandor/generated/globals.h   extern declarations
    src/generated/globals.c               definitions

Usage: python tools/gen_globals.py ghidra/thandor.exeV537.c
"""
import pathlib
import re
import sys

import infer_signatures

ROOT = pathlib.Path(__file__).resolve().parent.parent
# "Type[dims] *name;" where name may be a raw Ghidra string label such as u_engine\font.gfx_0041b030
# "Type *[8] name" is an array of 8 pointers, i.e. "Type *name[8]" in C
DECL = re.compile(r"^(?P<type>[A-Za-z_]\w*(?:\s+[A-Za-z_]\w*)*?)\s*(?P<ptr0>(?:\*\s*)*)(?P<dims>(?:\[\w+\])*)\s*(?P<ptr>(?:\*\s*)*)(?P<name>[^\s*].*?)\s*;\s*$")
# Globals the export types as undefined4 although every use treats them as one pointer type
# (NULL comparisons against that type, no integer arithmetic).
TYPE_OVERRIDES = {
    "g_InGameCommandPreviewArmyRuntime": "GameEntityRuntime *",
    "g_InGamePlacementPreviewArmyRuntime": "GameEntityRuntime *",
    "g_FatalErrorUiRootTemplate": "UiRootNode *",
}
STRING_TYPES = {"string": ("char", '"'), "TerminatedCString": ("char", '"'),
                "unicode": ("word", 'L"'), "TerminatedUnicode": ("word", 'L"')}
HEADER = """/*
 * Open Thandor
 * Project: https://github.com/idkFoxes/open-thandor/tree/main
 * Generated by tools/gen_globals.py from {src}. Do not edit by hand.
 */
"""


def function_names():
    """Every identifier that is called or declared as a function anywhere in the tree."""
    names = set()
    call = re.compile(r"\b([A-Za-z_]\w*)\s*\(")
    for p in list((ROOT / "include").rglob("*.h")) + list((ROOT / "src").rglob("*.c")):
        if p.name in ("types.h", "globals.h", "globals.c"):
            continue
        names.update(call.findall(strip_comments(p.read_text(encoding="utf-8", errors="replace"))))
    return names


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def unrecovered_signatures():
    """Names used as `Name *` whose spelling marks a function type (…Proc, …Callback, …Cf,
    …Handler) but which no header defines."""
    types_h = (ROOT / "include/thandor/generated/types.h").read_text(encoding="utf-8")
    export = (ROOT / "ghidra/thandor.exeV537.c").read_text(encoding="utf-8")
    used = set()
    pat = re.compile(r"\b([A-Za-z_]\w*(?:Proc|Callback|Cf|Handler))\s*\*")
    for text in [export] + [p.read_text(encoding="utf-8", errors="replace")
                            for p in list((ROOT / "include").rglob("*.h")) + list((ROOT / "src").rglob("*.c"))
                            if p.name not in ("globals.h", "globals.c")]:
        used.update(pat.findall(text))
    defined = lambda n: re.search(r"typedef[^;{]*\b" + n + r"\b\s*[(;\[]|\}\s*" + n + r"\b|struct\s+" + n + r"\b", types_h)
    return sorted(n for n in used if not defined(n))


RAM_TYPES = {"u": "dword", "i": "int", "p": "void *", "b": "byte", "c": "char", "s": "short",
             "us": "word", "ui": "dword", "pp": "void **", "pc": "char *", "pu": "dword *", "f": "float", "d": "double"}


def implicit_symbols(globals_):
    """Scan the split sources for Ghidra-invented symbol spellings."""
    text = "\n".join(strip_comments(p.read_text(encoding="utf-8", errors="replace"))
                     for p in (ROOT / "src").rglob("*.c") if p.parent.name != "generated")
    ram = sorted({(RAM_TYPES[m.group(1)], m.group(0))
                  for m in re.finditer(r"\b(us|ui|pp|pc|pu|[uipbcsfd])Ram([0-9a-f]{8})\b", text)}, key=lambda x: x[1])
    aliases = sorted({n for n in re.findall(r"\b_([gks]_\w+)", text) if n in globals_})
    literals = sorted(set(re.findall(r"\b(k_LowAddressLiteral([0-9A-Fa-f]{8}))\b", text)))
    return ram, aliases, literals


def find_block(lines):
    """The data block is the longest run of top-level `Type name;` lines."""
    best, start = (0, 0), None
    for i, line in enumerate(lines + [""]):
        ok = bool(DECL.match(line)) and not line.startswith(("typedef", " ", "\t", "//", "}", "struct", "union"))
        if ok and start is None:
            start = i
        elif not ok and line.strip() and start is not None:
            if i - start > best[1] - best[0]:
                best = (start, i)
            start = None
    return best


def main(export):
    src = pathlib.Path(export).resolve()
    lines = src.read_text(encoding="utf-8").splitlines()
    lo, hi = find_block(lines)
    funcs = function_names()
    decls, skipped, seen = [], [], set()
    for line in lines[lo:hi]:
        m = DECL.match(line)
        if not m:
            continue
        typ, label = m.group("type").strip(), m.group("name").strip()
        dims, ptr = m.group("dims"), (m.group("ptr0") + m.group("ptr")).replace(" ", "")
        # the split sources spell labels with every non-identifier char replaced by '_'
        name = re.sub(r"\W", "_", label)
        init = None
        if typ in STRING_TYPES and not dims and not ptr:
            typ, quote = STRING_TYPES[typ]
            dims = "[]"
            # Best-effort text from the label (prefix and _ADDRESS suffix stripped); verify against the exe.
            text = re.sub(r"^[su]_|_[0-9a-f]{8}$", "", label)
            text = text.replace("\\", "\\\\").replace('"', '\\"')
            init = f'{quote}{text}"'
        if name in seen:
            continue
        seen.add(name)
        if typ == "undefined" and name in funcs:
            skipped.append(name)
            continue
        full_type = TYPE_OVERRIDES.get(name, typ + (" " + ptr if ptr else ""))
        decls.append((full_type, name, dims, init))

    rel = src.relative_to(ROOT).as_posix()
    h = [HEADER.format(src=rel),
         "#ifndef THANDOR_GENERATED_GLOBALS_H",
         "#define THANDOR_GENERATED_GLOBALS_H",
         "",
         "#include <thandor/generated/types.h>",
         "",
         "/* Function-signature types Ghidra does not include in its C export. Unprototyped",
         " * placeholders: they accept any arguments. Replace with the real signature once recovered. */"]
    sigs = infer_signatures.infer(unrecovered_signatures(), [(t, n) for t, n, _, _ in decls])
    h += [infer_signatures.render(t, s) for t, s in sigs.items()]
    h += [""]
    h += [f"extern {t} {n}{d};" for t, n, d, _ in decls]
    ram, aliases, literals = implicit_symbols({n for _, n, _, _ in decls})
    h += ["", "/* Unnamed memory cells Ghidra prints as <type>Ram<address>; plain globals in this build. */"]
    h += [f"extern {t} {n};" for t, n in ram]
    h += ["", "/* _name: dword-sized access to the untyped label `name`. */"]
    h += [f"#define _{n} (*(dword *)&{n})" for n in aliases]
    h += ["", "/* Symbols Ghidra invented for absolute low addresses; `&sym` yields the constant. */"]
    h += [f"#define {n} (*(byte *)0x{a})" for n, a in literals]
    h += ["", "#endif /* THANDOR_GENERATED_GLOBALS_H */", ""]
    c = [HEADER.format(src=rel), "#include <thandor/thandor.h>", ""]
    c += [f"{t} {n}{d} = {i}; /* TODO: verify text against thandor.exe */" if i else f"{t} {n}{d};"
          for t, n, d, i in decls]
    c += [f"{t} {n};" for t, n in ram]
    c += [""]

    (ROOT / "include/thandor/generated/globals.h").write_text("\n".join(h), encoding="utf-8", newline="\n")
    out = ROOT / "src/generated/globals.c"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(c), encoding="utf-8", newline="\n")
    full = sum(1 for s in sigs.values() if s and s[0] == "full")
    ret = sum(1 for s in sigs.values() if s and s[0] == "ret")
    print(f"block lines {lo + 1}-{hi}: {len(decls)} globals, {len(skipped)} function labels skipped")
    print(f"signatures: {full} recovered, {ret} return-type only, {len(sigs) - full - ret} placeholders")


if __name__ == "__main__":
    main(sys.argv[1])
