"""Generate include/thandor/generated/imports.h from ghidra/export/imports.jsonl.

thandor.exe imports only KERNEL32 and USER32 statically (DirectX, Glide, WinSock and
winmm are resolved at runtime through LoadLibrary/GetProcAddress). The Win32 types come
from generated/types.h (Ghidra's Windows archive), so <windows.h> cannot be included;
these prototypes use those types with the real __stdcall/dllimport linkage.

Usage: python tools/gen_imports.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main():
    imports = [json.loads(l) for l in (ROOT / "ghidra/export/imports.jsonl").read_text(encoding="utf-8").splitlines()]
    h = ["/*",
         " * Open Thandor",
         " * Project: https://github.com/idkFoxes/open-thandor/tree/main",
         " * Generated by tools/gen_imports.py from ghidra/export/imports.jsonl. Do not edit by hand.",
         " */",
         "",
         "#ifndef THANDOR_GENERATED_IMPORTS_H",
         "#define THANDOR_GENERATED_IMPORTS_H",
         "",
         "#include <thandor/generated/types.h>",
         ""]
    for lib in sorted({d["library"] for d in imports}):
        h.append(f"/* {lib} */")
        for d in sorted((d for d in imports if d["library"] == lib), key=lambda d: d["name"]):
            params = ", ".join(f'{p["type"]} {p["name"]}' for p in d["params"]) or "void"
            if d["varargs"]:
                params += ", ..."
            h.append(f'__declspec(dllimport) {d["return"]} __stdcall {d["name"]}({params});')
        h.append("")
    h += ["#endif /* THANDOR_GENERATED_IMPORTS_H */", ""]
    (ROOT / "include/thandor/generated/imports.h").write_text("\n".join(h), encoding="utf-8", newline="\n")
    print(f"{len(imports)} imports")


if __name__ == "__main__":
    main()
