"""Generate src/generated/function_map.c: original entry address -> recovered C function.

The original data image (mapped by platform/bootstrap/image.c) stores code addresses in
callback tables, vtables and handler arrays. Every such dword that equals the entry of a
function the tree implements is redirected to the C function, so tables dispatch into the
recompiled code. Addresses of functions the tree does not implement stay untouched and are
reported by the loader when they are reached.

Usage: python tools/gen_function_map.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent


def defined_functions(names):
    """Names from `names` that have a definition (name, parameter list, body) somewhere in src/."""
    text = "\n".join(re.sub(r"/\*.*?\*/", " ", p.read_text(encoding="utf-8"), flags=re.S)
                     for p in (ROOT / "src").rglob("*.c") if p.parent.name != "generated")
    found = set(re.findall(r"(?<!\w)([A-Za-z_]\w*)\s*\([^;{}]*\)\s*\{", text))
    return {n for n in names if n in found}


# V537 program-database name -> older name still used by the split tree (matched by body).
ALIASES = {
    "ArmyRuntimeClass_UpdateResourceExtractionGridAndEffects": "ArmyRuntimeClass_UpdateGridBoundEffectsAndModels",
    "ArmyRuntimeClass_UpdateResourceStorageFillAndDamageEffect": "ArmyRuntimeClass_UpdateTransformAndDamageEffect",
    "ModelRuntimeSlotClassInit_AddFactionResourceStorageCapacityAndDetachRootChild1":
        "ModelRuntimeSlotClassInit_AccumulateFactionMetricAndDetachRootChild1",
    "ModelRuntimeSlotClassInit_AddFactionResourceStorageCapacityAndDetachRootChild3":
        "ModelRuntimeSlotClassInit_AccumulateFactionMetricAndDetachRootChild3",
    "ModelRuntimeSlotClassRelease_SubtractFactionResourceStorageCapacity": "ArmyPlacement_ReleaseFactionCapacity",
    "ModelRuntimeSlotClassRelease_SubtractFactionResourceStorageCapacityAndClearExtractionGridCell":
        "ArmyPlacement_ReleaseFactionCapacityAndClearGridReservation",
}


def main():
    functions = [json.loads(l) for l in (ROOT / "ghidra/export/functions.jsonl").read_text(encoding="utf-8").splitlines()]
    for f in functions:
        f["name"] = ALIASES.get(f["name"], f["name"])
    have = defined_functions({f["name"] for f in functions})
    entries = sorted({(int(f["address"], 16), f["name"]) for f in functions if f["name"] in have and not f["thunk"]})
    missing = sorted(f["name"] for f in functions if f["name"] not in have and not f["thunk"])
    c = ["/*",
         " * Open Thandor",
         " * Project: https://github.com/idkFoxes/open-thandor/tree/main",
         " * Generated by tools/gen_function_map.py from ghidra/export/functions.jsonl. Do not edit by hand.",
         " */",
         "",
         "#include <thandor/thandor.h>",
         "#include <thandor/platform/bootstrap/image.h>",
         "",
         "const ThandorFunctionMapEntry g_ThandorFunctionMap[] = {"]
    c += [f"    {{0x{a:08X}u, (void *)&{n}}}," for a, n in entries]
    c += ["};", "",
          f"const unsigned g_ThandorFunctionMapCount = {len(entries)}u;", ""]
    c += ["/* Functions of the original image without a recovered implementation: */"]
    c += [f"/*   {n} */" for n in missing]
    c += [""]
    (ROOT / "src/generated/function_map.c").write_text("\n".join(c), encoding="utf-8", newline="\n")
    print(f"{len(entries)} mapped functions, {len(missing)} without implementation: {missing}")


if __name__ == "__main__":
    main()
